In [1]:
import pandas as pd

dept_agents_df = pd.read_csv("../data/raw/agent_details.csv")

display(dept_agents_df.head())
display(dept_agents_df.shape)
display(dept_agents_df.dtypes)

,Agent ID,Name,Agent Type,Email,Phone Number,Department
0,e4e90091-6c3c-44e8-89c1-c2a6ab851b15,Christine Arnold,Full-time,emma68@example.net,(847)679-2854,Sales
1,3843d1ba-0fe8-43c4-95db-85431f587140,Sarah Chase,Full-time,angelaanderson@example.com,(500)667-3317,Technical
2,c72bc976-4e21-42d3-a344-df2d2176b1dc,Damon Smith,Full-time,hbrady@example.org,8542567120,Sales
3,e6cacfb3-112a-42fa-97d2-29ddc67b9759,Mary Simon,Contract,qparker@example.net,001-254-469-9283,Support
4,2acb7771-9ea7-4d53-9f8d-d3b24863b4cb,James Moore,Part-time,silvadenise@example.net,466.446.1426,Sales

(200, 6)

Agent ID        object
Name            object
Agent Type      object
Email           object
Phone Number    object
Department      object
dtype: object

In [2]:
import pandas as pd

call_abandonment_df = pd.read_csv("../data/raw/call_abandonment.csv")

display(call_abandonment_df.head())
display(call_abandonment_df.shape)
display(call_abandonment_df.dtypes)

,Call ID,Customer ID,Abandoned,Abandonment Reason,Call Duration Before Abandonment (mins)
0,6a46e92d-eea1-4b73-8280-e984be9062f2,67fceb4d-9979-458d-83d7-278bb72071a1,False,Not Interested,9.0
1,9f7701fa-e09c-492d-ad17-965d3f78d7cf,b0b60b98-c26b-4762-ab03-9cd12686a342,False,Not Interested,NaN
2,dc2f1429-8426-4adc-b2f6-a8c71936ac06,44eeb102-aa03-4409-bc45-d5167b02108a,True,Answered by Wrong Department,8.0
3,c33d4e40-43ea-48b7-a993-0963f4c51cf5,be62532a-b9d7-49a4-9592-ef3e2dffa42b,False,Long Wait Time,NaN
4,81b1bc42-ab35-4579-94c3-c5d732ef680a,f1bca76b-4a97-49ac-b51d-51ce2e861877,True,Long Wait Time,NaN

(5000, 5)

Call ID                                     object
Customer ID                                 object
Abandoned                                     bool
Abandonment Reason                          object
Call Duration Before Abandonment (mins)    float64
dtype: object

In [4]:
import pandas as pd

call_records_df = pd.read_csv("../data/raw/call_records.csv")

display(call_records_df.head())
display(call_records_df.shape)
display(call_records_df.dtypes)

,Call ID,Customer ID,Agent ID,Call Duration,Call Type,Issue
0,accc2764-24d5-47fa-8601-23ac1d7d89f0,b584550c-641c-44d0-b308-25381125d9b9,8d6d9486-30e2-40bc-8939-cdee700eebf1,50,Inbound,Complaint
1,befb90c0-aac5-4c6c-89c4-14f57d2ac30b,1be4ea93-a4b3-46fd-9f9f-7c48b1b196d2,b1f7f5f1-f9b1-4f1b-8ad3-ad6b623c40c0,67,Outbound,Complaint
2,b14d22ea-c0dd-40b3-8d18-9c82f3770b40,2320fd15-7b8d-4f1b-844e-d7716b6e8970,031914a4-aeb6-43f5-972d-9c718e2369f6,108,Outbound,Complaint
3,174f0491-3428-4d6e-b45a-7687c2811343,53fd6b84-3d16-4282-a4dc-2981250ea2de,ab4e938f-0f23-4966-b6f6-9f7286cacd45,83,Inbound,Technical Support
4,bcf0583e-a8e4-4ca6-8a69-b682d69ddd76,a2302e13-7a77-4091-81e5-701f959100ac,a47025c9-13bb-4e82-a5f9-5344b0e51c40,29,Inbound,Technical Support

(50000, 6)

Call ID          object
Customer ID      object
Agent ID         object
Call Duration     int64
Call Type        object
Issue            object
dtype: object

In [5]:
import pandas as pd

customer_satisfaction_df = pd.read_csv("../data/raw/customer_satisfaction.csv")

display(customer_satisfaction_df.head())
display(customer_satisfaction_df.shape)
display(customer_satisfaction_df.dtypes)

,Survey ID,Customer ID,Agent ID,Survey Date,Rating,Comments
0,f7534db5-4436-4732-ba2b-f484533e13dd,acb6e64b-b66f-4131-9f43-3c2ee7452132,afcbaef0-7f53-46c4-8527-8d76edc7f08c,2025-06-28,5,Glass only deep song growth character child. F...
1,09ab58c7-35a2-427f-98f5-cf9d6a3c9604,d09f1519-055b-4522-9c72-2344df538ca4,d8a94d44-48fc-45ff-b9b6-55f6faa22bc4,2025-04-01,4,Themselves performance soldier middle about gu...
2,e8674db2-76a0-41f3-be2d-cfc79c80d78e,92e5234d-1d5c-4052-adbb-69c4bc319511,9856a5e1-5c63-4f32-9e7c-6027c4832b43,2025-02-22,1,Statement say strong price. Pass billion at bu...
3,0034d910-2c68-4e46-a3a5-43cc2e5b4ce0,f56d08de-80e7-4dc5-bb3a-32c1149a2c10,2e40c3da-5387-4631-b279-e4c21135bf49,2025-06-15,4,Why reason debate theory college nation. Weigh...
4,eb231962-c292-4eb8-a73b-e8e9433744ab,e5debafb-ac78-4dc9-b49e-1590934173e6,067d6802-bbc2-46ba-aa62-bf9fc1b7e1b7,2025-07-09,4,Must within through. Successful capital centra...

(10000, 6)

Survey ID      object
Customer ID    object
Agent ID       object
Survey Date    object
Rating          int64
Comments       object
dtype: object

In [6]:
import pandas as pd

escalated_issues_df = pd.read_csv("../data/raw/escalated_issues.csv")

display(escalated_issues_df.head())
display(escalated_issues_df.shape)
display(escalated_issues_df.dtypes)

,Escalation ID,Customer ID,Agent ID,Issue Type,Escalation Reason,Escalated Department,Resolution Status
0,eb7ee6f4-641b-4a13-a9ab-46f75e9e319b,fd219147-0546-4e46-b97a-26de84690b9e,ebe8b5a4-caf3-46a0-a28f-09257af849f5,Billing Inquiry,Customer request,Specialist,Resolved
1,f7455727-fcc6-4a13-863c-a66649381351,d6d606cc-a60a-46fb-9ce9-98f6720384fc,1ed2f01a-7906-4b5a-935c-6e77f4629d18,Technical Support,Customer request,Management,Pending
2,532c5105-87c0-4abc-a331-dac3570ffd06,0073e1bc-a5a4-4348-b3b3-5d4e5e92eb75,11c275d9-0665-4d23-8db3-bab08b992b19,Technical Support,Policy issue,Support,Closed
3,1082529b-bed0-4287-90d6-e895e2e9d7e9,383338d7-c373-41d7-9e51-d5cad7a0a77e,4c92c7ea-2a5e-4254-bb4d-d9033d98b8ab,Technical Support,Policy issue,Specialist,Pending
4,3fa6be7a-5f42-452e-9cbf-0030f0667912,7ac86e03-e281-4e23-b5c3-bfd2a2017d38,e09ad210-5a3f-4eff-905e-2ad29b22febe,Complaint,Policy issue,Specialist,Pending

(5000, 7)

Escalation ID           object
Customer ID             object
Agent ID                object
Issue Type              object
Escalation Reason       object
Escalated Department    object
Resolution Status       object
dtype: object